import Status from '@/components/StatusFilter';
import NFTView from '@/view/NFTView';
import Head from 'next/head';
import { useState } from 'react';

const TABINFORM = [
  { idx: 0, name: 'NFT', content: <NFTView /> },
  { idx: 1, name: '컬렉션 정보', content: '컬렉션 정보의 내용' },
  { idx: 2, name: '액티비티', content: '액티비티의 내용' },
];

export default function Home() {
  const [tabIndex, setTabIndex] = useState<number>(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ul style={{ display: 'flex', listStyleType: 'none' }}>
        {TABINFORM.map((ele) => {
          return (
            <li
              style={{ outline: '1px solid red', padding: '10px' }}
              key={ele.idx}
              onClick={() => {
                setTabIndex(ele.idx);
              }}
            >
              {ele.name}
            </li>
          );
        })}
      </ul>
      <div>{TABINFORM[tabIndex].content}</div>
    </>
  );
}
