import Head from 'next/head';
import { useState } from 'react';

import Status from '@/components/StatusFilter';
import Tabs from '@/components/Tabs';
import TabContent from '@/components/TabContent';

import NFTView from '@/view/NFTView';

const COLLECTION_TABS = [
  { idx: 0, name: 'NFT', content: <NFTView /> },
  { idx: 1, name: '컬렉션 정보', content: '컬렉션 정보의 내용' },
  { idx: 2, name: '액티비티', content: '액티비티의 내용' },
];

export default function Home() {
  const [tabIndex, setTabIndex] = useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Tabs tabs={COLLECTION_TABS} setTabIndex={setTabIndex} />
      <TabContent content={COLLECTION_TABS[tabIndex].content} />
    </>
  );
}
